config/routes.rb
Ep::Application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: "registrations",
    sessions: "sessions",
    passwords: "passwords"
  }

  devise_scope :user do
    authenticated :user do
      root :to => 'users#show', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/registrations#new'
    end
  end

  resources :users do
    get :autocomplete_college_name, :on => :collection
    member do
      put :add_avatar
      put :remove_avatar
      put :add_resume
      put :remove_resume
      get :my_jobs
      get :refresh_progress
    end

    authenticate :user do
      resources :conversations do
        member do
          put :restore
        end
      end
    end

    resources :connections, only: [:index]
  end

  resources :colleges, only: [:create]
  resources :college_infos, only: [:edit, :update, :destroy]
  resources :experiences, only: [:create, :edit, :update, :destroy]
  resources :skills, only: [:create, :destroy]
  resources :certs, only: [:create, :destroy]
  resources :roles, only: [:create, :destroy]
  resources :subjects, only: [:create, :destroy]
  resources :job_posts
  resources :messages
  resources :job_maps, only: [:index]
  resources :friendships, only: [:create, :update, :destroy]

  resources :orgs, only: [:show, :index, :update]

  get '/terms' => 'pages#terms', as: :terms
  get '/privacy_policy' => 'pages#privacy_policy', as: :privacy_policy

end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    connection_type = params[:connection_type]

    case connection_type
    when 'suggestions'
      @connections = Ep::Lib.get_suggestions(@user)
      @title = 'Suggestions'
    when 'friends'
      @connections = @user.friends
      @title = 'My Connections'
    when 'pending_invited'
      @connections = @user.pending_invited
      @title = 'Sent Requests'
    when 'pending_invited_by'
      @connections = @user.pending_invited_by
      @title = 'Invitations to Connect'
    end
  end
end

app/views/connections/_connection.html.erb
<div id="ep-connection" class="ep-connection">
	<p>
		<span class="ep-connection__photo">
			<%= user_image(friend, 'thumb', '50', '50') %>
	  </span>
	  <div style="padding-left:60px;">
			<%= link_to friend.name, user_path(friend) %><br>
			<span class="ep-gray ep-connection__headline">
				<p style="height:20px;"><%= friend.headline.truncate(45) if friend.headline.present? %></p>
			</span>
		</div>
	</p>
		<% if user_signed_in? && current_user == user %>
			<% if (current_user.invited_by? friend) && (!current_user.friend_with? friend) %>
				<div class="ep-connection-choice">
					<%= link_to friendship_path(friend), method: :put, remote: true, class: 'ep-approve' do %>
						 <i class="fa fa-plus"></i> Approve
					<% end %>
					&nbsp|&nbsp
					<%= link_to friendship_path(friend), method: :delete, remote: true, class: 'ep-deny' do %>
						<i class="fa fa-minus"></i> Decline
					<% end %>
				</div>
			<% elsif (current_user.friend_with? friend) %>
				<div class="ep-connection-choice">
					<%= link_to friendship_path(friend), method: :delete, remote: true, class: 'ep-deny' do %>
						<i class="fa fa-minus"></i> Remove
					<% end %>
				</div>
			<% end %>
		<% end %>
	<hr style="clear:both">
</div>

app/views/connections/_connections.html.erb
<div class="ep-profile-section__header">
	<h4>Connections</h4>
</div>

<div class="ep-profile-section__body">

	<div class="ep-connections">
    <% if user == current_user %>
        <a id="ep-show-suggested-friends" class="ep-active-connections">Suggestions</a>
		  | <a id="ep-show-friends">Connections</a>
			| <a id="ep-show-invites">Sent</a>
      | <a id="ep-show-inviters">Invitations</a>
      <% if user.pending_invited_by.count > 0 %>
        <span class="ep-unread-messages-alert"><%= user.pending_invited_by.count > 0 ? user.pending_invited_by.count : "" %></span>
      <% end %>
    <% else %>
      <p>Connections <%= user.friends.count > 0 ? "(#{user.friends.count})" : "" %></p>
		<% end %>
	</div>

  <% if user == current_user %>
    <div id="ep-friend-suggestions">
      <% for friend in suggestions.take(4) %>
        <%= render partial: 'connections/connection', locals: { friend: friend, user: user } %>
      <% end %>
      <% if suggestions.count > 4 %>
        <%= link_to 'See more', user_connections_path(user, connection_type: 'suggestions'), remote: true %>
      <% end %>
    </div>
  <% end %>

	<div id="ep-friends">
		<% for friend in user.friends.take(4) %>
			<%= render partial: 'connections/connection', locals: { friend: friend, user: user } %>
		<% end %>
    <% if user.friends.blank? %>
      <div class="ep-no-friends">
        No connections yet. <%= link_to 'Find connections.', users_path() %>
      </div>
    <% end %>
    <% if user.friends.count > 4 %>
      <%= link_to 'See all', user_connections_path(user, connection_type: 'friends'), remote: true %>
    <% end %>
	</div>
	<% if user == current_user %>
		<div id="ep-invited">
			<% for invite in user.pending_invited.take(4) %>
				<%= render partial: 'connections/connection', locals: { friend: invite, user: user } %>
			<% end %>
      <% if user.pending_invited.blank? %>
        <div class="ep-no-friends">
          You haven't sent any invitations.
        </div>
      <% end %>
      <% if user.pending_invited.count > 4 %>
        <%= link_to 'See all', user_connections_path(user, connection_type: 'pending_invited'), remote: true %>
      <% end %>
		</div>

		<div id="ep-invited_by">
			<% for inviter in user.pending_invited_by.take(4) %>
				<%= render partial: 'connections/connection', locals: { friend: inviter, user: user } %>
			<% end %>
      <% if user.pending_invited_by.blank? %>
        <div class="ep-no-friends">
          No invitations.
        </div>
      <% end %>
      <% if user.pending_invited_by.count > 4 %>
        <%= link_to 'See all', user_connections_path(user, connection_type: 'pending_invited_by'), remote: true %>
      <% end %>
		</div>
	<% end %>
</div>

<div class="modal fade ep-connection-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
</div>

app/views/connections/_more_connections.html.erb
<div class="modal-dialog modal-sm">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title"><%= @title %></h4>
    </div>
    <% for friend in connections %>
      <%= render partial: 'connections/connection', locals: { friend: friend, user: user } %>
    <% end %>
  </div>
</div>