config/routes.rb
Ep::Application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: "registrations",
    sessions: "sessions",
    passwords: "passwords"
  }

  devise_scope :user do
    authenticated :user do
      root :to => 'users#show', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/registrations#new'
    end
  end

  resources :users do
    get :autocomplete_college_name, :on => :collection
    member do
      put :add_avatar
      put :remove_avatar
      put :add_resume
      put :remove_resume
      get :my_jobs
      get :refresh_progress
    end

    authenticate :user do
      resources :conversations do
        member do
          put :restore
        end
      end
    end

    resources :connections, only: [:index]
  end

  resources :colleges, only: [:create]
  resources :college_infos, only: [:edit, :update, :destroy]
  resources :experiences, only: [:create, :edit, :update, :destroy]
  resources :skills, only: [:create, :destroy]
  resources :certs, only: [:create, :destroy]
  resources :roles, only: [:create, :destroy]
  resources :subjects, only: [:create, :destroy]
  resources :job_posts
  resources :messages
  resources :job_maps, only: [:index]
  resources :friendships, only: [:create, :update, :destroy]

  resources :orgs, only: [:show, :index, :update]

  get '/terms' => 'pages#terms', as: :terms
  get '/privacy_policy' => 'pages#privacy_policy', as: :privacy_policy

end

app/models/org.rb
class Org
  include Mongoid::Document
  include Mongoid::Timestamps
  include Geocoder::Model::Mongoid

  after_validation :geocode
  geocoded_by :address_or_name_for_geocode

  field :name,            type: String
  field :about,           type: String
  field :org_website,     type: String
  field :org_type,        type: String
  field :owner,           type: String

  field :borough,         type: String
  field :neighborhood,    type: String
  field :street_address,  type: String
  field :city,            type: String
  field :state,           type: String
  field :zip,             type: String
  field :coordinates,     :type => Array

  has_one :user
  has_many :job_posts

  def address
    "#{self.street_address} #{self.city} #{self.state} #{self.zip}"
  end

  private

  def address_or_name_for_geocode
    if self.street_address.present?
      return self.address
    else
      return self.name
    end
  end
end

app/controllers/orgs_controller.rb
class OrgsController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @search_term = params[:search]
    @locations = Location.all.asc(:name)

    locations = params[:filter_by_locations]

    if locations
      @orgs = User.just_orgs
    else
      @orgs = User.just_orgs.asc(:created_at).paginate(page: params[:page], per_page: 10)
    end

    if @search_term.present? || locations
      @orgs = User.just_orgs.full_text_search(@search_term) if @search_term.present?

      if locations
        real_orgs = Org.in(borough: locations)
        @orgs = @orgs.in(org_id: real_orgs.map { |org| org.id.to_s })
      end
      @orgs = @orgs.paginate(page: params[:page], per_page: 10)
    end
  end

  def show
    if params[:id]
      @org_user = User.find params[:id]
      @org = @org_user.org
    else
      @org_user = current_user
      @org = current_user.org
    end
    @suggestions = User.where(as_org: true).shuffle.first(3)

    if current_user
      @conversations = @org_user.conversations.where(removed_for_ids: { '$nin' => [current_user.id.to_s] })
      @unread_messages_count = @org_user.unread_messages_count(@conversations)
    end
  end

  def update
    @org = Org.find(params[:id])
    @org.update_attributes(params[:org])

    if params[:address_update]
      redirect_to user_path(@org.user)
    else
      render nothing: true
    end
  end

  private

end

app/views/orgs/_about.html.erb
<div class="ep-profile-section__header">
	<h4>
		About
	</h4>
</div>

<div class="ep-profile-section__body js-section-container">

  <p class="<%= org.about.present? ? '' : 'ep-gray'%>">
    <% if org.user == current_user %>
      <%= best_in_place org, :about,
        :type => :textarea,
        activator: '.ep-edit-about',
        nil: 'Tell us about your organization.',
        :html_attrs => { :style => 'width:460px; height: 100px;' }
      %> <br>
      <% if org.about.present? %>
        <a class="ep-edit-about js-edit"> Edit</a>
      <% else %>
        <a class="ep-edit-about js-add-bip"> + Add</a>
      <% end %>
    <% else %>
      <p><%= org.about %></p>
    <% end %>
  </p>
</div>

app/views/orgs/_connection.html.erb
<div id="ep-connection" class="ep-connection">
	<p>
		<span class="ep-connection__photo">
			<%= user_image(user, 'thumb', '50', '50') %>
	  </span>
	  <div style="padding-left:60px;">
			<%= link_to user.name, user_path(user) %><br>
			<span class="ep-gray ep-connection__headline">
				<p style="height:20px;"><%= user.headline.truncate(45) if user.headline.present? %></p>
			</span>
		</div>
	</p>
		<% if current_user %>
			<% if (current_user.invited_by? user) && (!current_user.friend_with? user) %>
				<div class="ep-connection-choice">
					<%= link_to approve_friend_user_path(user), method: :put, remote: true, class: 'ep-approve' do %>
						 <i class="fa fa-plus"></i> Approve
					<% end %>
					&nbsp|&nbsp
					<%= link_to remove_deny_friend_user_path(user), method: :put, remote: true, class: 'ep-deny' do %>
						<i class="fa fa-minus"></i> Decline
					<% end %>
				</div>
			<% elsif current_user.friend_with? user %>
				<div class="ep-connection-choice">
					<%= link_to remove_deny_friend_user_path(user), method: :put, remote: true, class: 'ep-deny' do %>
						<i class="fa fa-minus"></i> Remove
					<% end %>
				</div>
			<% end %>
		<% end %>
	<hr style="clear:both">
</div>

app/views/orgs/_org_jobs.html.erb
<div class="ep-profile-section__header">
  <h4>
    Jobs Posted
    <% if org.user == current_user %>
      <a class="pull-right" data-toggle="collapse" data-target="#ep-app-job__toggle">Post a job</a>
    <% end %>
  </h4>
  <% if org.user == current_user %>
    <div id="ep-app-job__toggle" class="collapse">
      <div class='ep-form'>
        <%= form_for JobPost.new do |f| %>
          <%= render partial: 'job_posts/form_fields', locals: { f: f, org: org } %>
          <div class="ep-form__clear">
            <%= f.submit 'Add', :class => 'btn btn-primary' %>
            <%= content_tag :div, 'cancel', class: 'btn btn-default', :data => { toggle: "collapse", target: "#ep-app-job__toggle" } %>
            <br><br>
            <p class="ep-gray">This job post will expire in 90 days.</p>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="ep-profile-section__body js-section-container">
  <% if org.user.job_posts.present? %>
    <% org.user.job_posts.desc(:created_at).limit(3).each do |job| %>
      <p><%= link_to job.title, job_post_path(job) %> | <span class='ep-gray'>Posted on <%= job.created_at.strftime("%B %-d") %></span></p> <br>
      <p><%= job.description.truncate(200) %></p>
      <hr>
    <% end %>
    <% if org.user.job_posts.count > 3 %>
      <%= link_to 'View all', my_jobs_user_path(org.user) %>
    <% end %>
  <% else %>
    <p class='ep-gray'>No jobs posted</p>
  <%end%>
</div>

app/views/orgs/_org_map.html.erb
<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['EP_GOOGLE_MAPS_KEY'] %>">
</script>

<% lng = org.coordinates[0] %>
<% lat = org.coordinates[1] %>

<script type="text/javascript">

  var myLatlng = new google.maps.LatLng(<%= lat %>,<%= lng %>);

  var styles = [{"featureType":"landscape.natural","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"color":"#e0efef"}]},{"featureType":"poi","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"hue":"#1900ff"},{"color":"#d3d3d3"}]},{"featureType":"road","elementType":"geometry","stylers":[{"lightness":100},{"visibility":"simplified"}]},{"featureType":"transit.line","elementType":"geometry","stylers":[{"visibility":"on"},{"lightness":700}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#3bafda"}]}]

  function initialize() {
    var mapOptions = {
      center: myLatlng,
      zoom: 12,
      styles: styles
    };
    var map = new google.maps.Map(document.getElementById('map-canvas'),
        mapOptions);

    var marker = new google.maps.Marker({
      position: myLatlng,
      title:"<%= org.name %>"
    });

    marker.setMap(map);
  }
  google.maps.event.addDomListener(window, 'load', initialize);

</script>

<div class="ep-profile-section__header">
  <h4>
    Location
  </h4>
</div>
<div class="ep-profile-section__body ep-profile-section__map js-section-container">
  <% if current_user == org.user && org.street_address.blank? %>
    <a href="" class="xpnd-not-your-address" data-toggle="modal" data-target=".ep-address-modal">Not your location?</a>
  <% end %>
  <div id="map-canvas" style="width: 89%; height: 81%; position: absolute;"></div>
</div>

<div class="modal fade ep-address-modal" tabindex="-1" role="dialog" aria-labelledby="myMadalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content ep-content--send-message">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Change Your address:</h4>
      </div><br>
      <%= form_for org do |f| %>
        <%= hidden_field_tag :address_update, true %>
        <%= f.text_field :street_address, :class => '', placeholder: 'Street address', style: 'width: 92%' %> <br> <br>
        <%= f.text_field :city, :class => 'ep-form__small-input', placeholder: 'City', style: "width:176px" %>
        <%= f.text_field :state, :class => 'ep-form__small-input', placeholder: 'State', style: "width:54px" %>
        <%= f.text_field :zip, :class => 'ep-form__small-input', placeholder: 'Zip code', style: "width:82px" %> <br><br><br>
        <%= f.submit 'Save', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/orgs/_org_website.html.erb
<div class="ep-profile-section__header">
  <h4>
    Website
  </h4>
</div>

<div class="ep-profile-section__body js-section-container">
  <p class="<%= org.org_website.present? ? '' : 'ep-gray'%>">
    <% if org.user == current_user %>
      <%= best_in_place org, :org_website,
        type: :input,
        activator: '.ep-edit-website',
        display_with: lambda { |url| "<a href='http://#{url}' target='_blank'>#{url}</a>".html_safe },
        nil: 'Add your website here.'
      %> <br>
      <% if org.org_website.present? %>
        <a class="ep-edit-website js-edit"> Edit</a>
      <% else %>
        <a class="ep-edit-website js-add-bip"> + Add</a>
      <% end %>
    <% else %>
      <p><%= link_to org.org_website, "http://#{org.org_website}", target: '_blank' %></p>
    <% end %>
  </p>
</div>

app/views/orgs/_orgs.html.erb
<% if users.present? %>
  <% users.each do |org_user| %>
    <tr>
      <td class="ep-index__org-main-info">
        <div class="ep-index__photo">
          <%= user_image(org_user, 'thumb', '50', '50') %>
        </div>
        <div class="ep-index__meta">
          <% if org_user.org.present? %>
            <p class="ep-index__meta--name"><%= link_to org_user.org.name, org_path(org_user) %></p>
          <% end %>
          <p class="ep-index__meta-content">
            <%= org_user.org.borough %><br>
            <%= org_user.org.org_type %>
          </p>
        </div>
      </td>
      <% if current_user %>
        <td>
          <div class="ep_index--connection js_users--connection-<%= org_user.id %>">
            <%= render partial: 'orgs/user_connection', locals: { user: org_user } %>
          </div>
        </td>
      <% end %>
    </tr>
  <% end %>
<% else %>
  <p>Sorry, no matches. Try broadening your search.</p>
<% end %>

app/views/orgs/_profile_actions.html.erb
<% if !user_signed_in? %>
  <p><i class="fa fa-plus"></i>&nbsp <%= link_to "Sign in", new_session_path(org_user) %> to connect</p>

<% elsif current_user == org_user %>
  <% %>

<% elsif !current_user.connected_with? org_user %>
  <p class='ep-profile-connection-request'>
    <i class="fa fa-plus"></i>
    <span class='ep-profile-connection-request-link ep-link-style' data-toggle="modal" data-target="#ep-confirm__connection-request">
      Connect
    </span>
  </p>

<% elsif current_user.friend_with? org_user %>
  <p><i class="fa fa-users"></i>&nbsp Connected</p>

<% elsif current_user.invited? org_user %>
  <p><i class="fa fa-plus"></i>
  Pending connection
  </p>

<% elsif current_user.invited_by? org_user %>
  <p><i class="fa fa-plus"></i>
  Pending connection
  <%= link_to "(Approve)", friendship_path(org_user), method: :put, remote: true, class: 'ep-approve' %></p>

<% end %>

<% if user_signed_in? %>
  <% if current_user == org_user %>
    <p>
      <i class="fa fa-envelope"></i> <%= link_to 'Messages', user_conversations_path(org_user) %>
      <% if @unread_messages_count > 0 %>
        <span class="ep-unread-messages-alert"><%= "#{@unread_messages_count}" %></span>
      <% end %>
    </p>
  <% else %>
    <p data-toggle="modal" data-target=".ep-message-modal">
      <i class="fa fa-envelope"></i>&nbsp<a>Send a message</a>
    </p>
  <% end %>
<% else %>
  <p><i class="fa fa-envelope"></i>&nbsp <%= link_to "Sign in", new_session_path(org_user) %> to send a message</p>
<% end %>

<% if current_user == org_user %>
  <p class='js-edit-mode'><i class="fa fa-pencil-square"></i><a> Edit my profile</a></p>
  <p class='js-exit-edit-mode js-edit'><i class="fa fa-pencil-square"></i><a> Done Editing</a></p>
<% end %>

<div id="ep-confirm__connection-request" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content ep-content--send-message">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <div class="modal-header">
        <h4 class="modal-title modal-title--gray">Connect with <%= org.name %>?</h4>
      </div><br>
      <div class="ep-confirm__btns">
        <%= link_to "Connect", friendships_path(id: org.id), method: :post, remote: true, class: 'btn btn-primary', data: { dismiss: "modal"} %>
        <div class="ep-cancel-edit btn btn-default" data-dismiss="modal">cancel</div>
      </div>
    </div>
  </div>
</div>

app/views/orgs/_profile_header.html.erb
<div class="col-sm-12 ep-profile-header white-bg">

	<div class="row">
		<div class="col-sm-6 ep-user-snapshot">
			<div class="ep-profile-image">
				<%= user_image(org_user, 'medium', '120', '120') %>
			 	<% if org_user == current_user %>
					<div class="ep-profile-image__uploader-container">
						<a class="ep-change-image <%= org_user.has_profile_image? ? 'js-edit' : '' %>" data-toggle="collapse" data-target="#ep-profile-image__toggle">
							<i class="fa fa-camera-retro"></i>
							<%= org_user.has_profile_image? ? 'Change image' : 'Add image' %>
						</a>
					</div>
				<% end %>
			</div>

			<div class="ep-user-info ep-user-info--org">
				<h3>
					<%= best_in_place org, :name, :type => :input, activator: '.ep-edit-org-name' %>
					<% if org_user == current_user %>
						<a class="ep-edit-org-name js-edit"> Edit</a>
					<% end %>
				</h3>
				<% if org.org_type.present? || current_user == org_user %>
					<p>
						<%= best_in_place org, :org_type, :type => :input, activator: '.ep-edit-org-type', nil: 'What type of organization are you?' %>
						<% if org_user == current_user %>
							<% if org.org_type.present? %>
								<a class="ep-edit-org-type js-edit"> Edit</a>
							<% else %>
								<a class="ep-edit-org-type js-add-bip"> + Add</a>
							<% end %>
						<% end %>
					</p>
				<% end %>
				<% if org.borough.present? || current_user == org_user %>
					<p>
						<%= best_in_place org, :borough, :type => :input, activator: '.ep-edit-org-borough', nil: 'What\'s your borough or county?' %>
						<% if org_user == current_user %>
							<% if org.borough.present? %>
								<a class="ep-edit-org-borough js-edit"> Edit</a>
							<% else %>
								<a class="ep-edit-org-borough js-add-bip"> + Add</a>
							<% end %>
						<% end %>
					</p>
				<% end %><br>
			</div>
		</div>

		<div class="ep-user-roles-and-subjects col-sm-3">
		</div>

		<div class="ep-profile-actions js-profile-actions-<%= org_user.id %> col-sm-3">
			<%= render partial: 'profile_actions', locals: { org: org, org_user: org_user} %>
		</div>
	</div>
	<%= render partial: 'users/add_avatar_form', locals: { user: org_user } %>
</div>

app/views/orgs/_user_connection.html.erb
<% unless user == current_user %>
  <% if user.friend_with? current_user %>
    <p class="ep-index__info-right">Connected</div>
  <% elsif user.invited_by? current_user %>
    <%= link_to 'Cancel request', friendship_path(user), method: :delete, remote: true, class: 'ep-index__info-right' %>
  <% elsif user.invited? current_user%>
    <div class="ep-connection-choice">
      <%= link_to 'Approve', friendship_path(user), method: :put, remote: true, class: 'ep-approve ep-index__info-right' %>
      &nbsp|&nbsp
      <%= link_to 'Decline', friendship_path(user), method: :delete, remote: true, class: 'ep-deny ep-index__info-right'%>
    </div>
  <% else %>
    <span class='ep-index__connect ep-index__info-right ep-link-style' data-toggle="modal" data-target="#ep-confirm__connection-request-<%= user.id %>">
      Connect
    </span>
  <% end %>

  <div id="ep-confirm__connection-request-<%= user.id %>" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content ep-content--send-message">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <div class="modal-header">
          <h4 class="modal-title modal-title--gray">Connect with <%= user.name %>?</h4>
        </div><br>
        <div class="ep-confirm__btns">
          <%= link_to "Connect", friendships_path(id: user.id), class: 'btn btn-primary', method: :post, remote: :true, data: { dismiss: "modal"} %>
          <div class="ep-cancel-edit btn btn-default" data-dismiss="modal">cancel</div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/orgs/add_password.html.erb
<div class="col-sm-12 ep-main-container">
  <div class="row">
    <div class="row">
      <%= form_for @user, html: { class: 'form-horizontal' } do |f| %>
        <div class="col-sm-4 col-sm-offset-4">
          <div class="ep-profile-section white-bg">
            <div class="ep-profile-section__header">
              <h4>Add a Password</h4>
            </div>
            <p class="ep-add-password-text"><strong>Hey, <%= @user.first_name %>!</strong> Here you can add a password that you can use to sign in when you come back next.</p>
            <div class="ep-profile-section__body ep-profile-section__body--add-password">
              <div class="ep-form__profile-form-field">
                <%= f.label :Password, class: 'ep-form__label' %><br>
                <%= f.password_field :password, autocomplete: "off", class: 'ep-form__text-field' %>
              </div>

              <div class="ep-form__profile-form-field">
                <%= f.label :password_confirmation, class: 'ep-form__label' %><br>
                <%= f.password_field :password_confirmation, autocomplete: "off", class: 'ep-form__text-field' %>
              </div>
            </div>
            <div class="form-actions ep-form-actions--add-password">
              <%= f.submit 'Save', class: 'btn btn-primary' %>
              <%= link_to t('.cancel', default: t("helpers.links.cancel")), user_path(current_user), class: 'ep-cancel-edit btn btn-default' %>
            </div><br>
            <div class="ep-profile-section__hr-line"></div><br>
            <p class="ep-add-password-text ep-italic">Clicking cancel will bring you to your profile, and you will need to sign in through LinkedIn next time you visit edPeople.</p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/orgs/edit.html.erb
<div class="col-sm-12 ep-main-container">
  <div class="row">
    <div class="row">
      <%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
        <div class="col-sm-4">
          <div class="ep-profile-section ep-account-settings-section white-bg">
            <div class="ep-profile-section__header">
              <h4>Personal Information</h4>
            </div>
            <div class="ep-profile-section__body">
              <div class="ep-form__profile-form-field">
                <%= f.label :email, :class => 'ep-form__label' %><br>
                <%= f.text_field :email, :class => 'ep-form__text-field' %>
              </div>
            </div>
          </div>
        </div>

        <div class="col-sm-4">
          <div class="ep-profile-section ep-account-settings-section white-bg">
            <div class="ep-profile-section__header">
              <h4>Notifications</h4>
            </div>
            <div class="ep-profile-section__body">
              <div class="ep-form__profile-form-field">
               Coming soon
              </div>
            </div>
          </div>
        </div>

        <div class="col-sm-4">
          <div class="ep-profile-section ep-account-settings-section white-bg">
            <div class="ep-profile-section__header">
              <h4>Change Password</h4>
            </div>
            <div class="ep-profile-section__body">
              <div class="ep-form__profile-form-field">
                <%= f.label :Password, :class => 'ep-form__label' %><br>
                <%= f.password_field :password, placeholder: "New password", :autocomplete => "off", :class => 'ep-form__text-field' %>
              </div>

              <div class="ep-form__profile-form-field">
                <%= f.label :password_confirmation, :class => 'ep-form__label' %><br>
                <%= f.password_field :password_confirmation, placeholder: "Confirm new password", :autocomplete => "off", :class => 'ep-form__text-field' %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row"><br>
        <div class="form-actions container">
          <div class="pull-right">
            <%= f.submit 'Save', :class => 'btn btn-primary' %>
            <%= link_to t('.cancel', :default => t("helpers.links.cancel")), user_path(current_user), :class => 'ep-cancel-edit btn btn-default' %>
            <span class='btn btn-primary btn-warning' data-toggle="modal" data-target="#ep-confirm__delete-account">
              Delete account
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div id="ep-confirm__delete-account" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content ep-content--send-message">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <div class="modal-header">
        <h4 class="modal-title modal-title--gray">Are you sure you want to delete your account?</h4>
      </div><br>
      <div class="ep-confirm__btns">
        <%= link_to 'Delete account', user_path(@user),
          method: :delete,
          class: 'btn btn-primary btn-warning'
        %>
        <div class="ep-cancel-edit btn btn-default" data-dismiss="modal">cancel</div>
      </div>
    </div>
  </div>
</div>

app/views/orgs/index.html.erb
<div class="row-fluid"><br><br><br><br>
  <div class="ep-search col-sm-3 white-bg">
    <h3>Find organizations</h3>
    <%= form_tag orgs_path, method: :get, remote: true, class: 'js-search-form' do %>

      <%= text_field_tag 'search', @search_term, placeholder: 'Search organizations...', class: "js-search-form__text-field ep-search-form__text-field" %>

      <h4>Filter by location</h4>
      <% @locations.each do |location| %>
        <%= check_box_tag 'filter_by_locations[]', location.name, false, id: "#{location.id}", class: 'js-search-form__check-box' %>
        <%= label_tag 'filter_by_location', location.name, class: 'ep-filter-label', for: "#{location.id}" %><br>
      <% end %>

    <% end %>
  </div>

  <div class="ep-index col-sm-8 white-bg">
    <div class="page-header">
      <h3>Organizations</h3>
    </div>
    <table class="table ep-index__table">
      <tbody class="ep-index__items">
        <%= render partial: 'orgs/orgs', locals: { users: @orgs } %>
      </tbody>
    </table>
    <div class="js-will-page">
      <%= will_paginate @orgs %>
    </div>
  </div>
</div>

app/views/orgs/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/orgs/show.html.erb
<div class="col-sm-12 ep-main-container">
	<div class="row">
		<div class="col-sm-12">
			<%= render partial: 'profile_header', locals: { org: @org, org_user: @org_user } %>
		</div>
		<div class="col-sm-7">
      <div class="ep-profile-section ep-profile-section--skill white-bg">
        <%= render partial: 'org_website', locals: { org: @org } %>
      </div>

			<div class="ep-profile-section white-bg">
				<%= render partial: 'about', locals: { org: @org } %>
			</div>

			<div class="ep-profile-section ep-profile-section--experience  white-bg">
				<%= render partial: 'org_jobs', locals: { org: @org } %>
			</div>
		</div>

		<div class="col-sm-5">
      <% if @org.coordinates.present? %>
        <div class="ep-profile-section ep-profile-section--skill white-bg">
          <%= render partial: 'org_map', locals: { org: @org } %>
        </div>
      <% end %>

			<div class="ep-profile-section js-profile-section--connections white-bg">
				<%= render partial: 'connections/connections', locals: { user: @org.user, suggestions: @suggestions } %>
			</div>
		</div>
	</div>
</div>

<div class="modal fade ep-message-modal" tabindex="-1" role="dialog" aria-labelledby="myMadalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content ep-content--send-message">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Send <%= @org.name %> a message</h4>
      </div><br>
      <%= form_for Message.new do |f| %>
        <%= hidden_field_tag :recipient_id, @org_user.id %>
        <%= f.text_area :note, :class => 'ep-form__text-area', rows: '3', cols: '50' %>
        <%= f.submit 'Send', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>