config/routes.rb
Ep::Application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: "registrations",
    sessions: "sessions",
    passwords: "passwords"
  }

  devise_scope :user do
    authenticated :user do
      root :to => 'users#show', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/registrations#new'
    end
  end

  resources :users do
    get :autocomplete_college_name, :on => :collection
    member do
      put :add_avatar
      put :remove_avatar
      put :add_resume
      put :remove_resume
      get :my_jobs
      get :refresh_progress
    end

    authenticate :user do
      resources :conversations do
        member do
          put :restore
        end
      end
    end

    resources :connections, only: [:index]
  end

  resources :colleges, only: [:create]
  resources :college_infos, only: [:edit, :update, :destroy]
  resources :experiences, only: [:create, :edit, :update, :destroy]
  resources :skills, only: [:create, :destroy]
  resources :certs, only: [:create, :destroy]
  resources :roles, only: [:create, :destroy]
  resources :subjects, only: [:create, :destroy]
  resources :job_posts
  resources :messages
  resources :job_maps, only: [:index]
  resources :friendships, only: [:create, :update, :destroy]

  resources :orgs, only: [:show, :index, :update]

  get '/terms' => 'pages#terms', as: :terms
  get '/privacy_policy' => 'pages#privacy_policy', as: :privacy_policy

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Amistad::FriendModel
  include Mongoid::Paperclip
  include Mongoid::Search

  scope :just_users, lambda { where(as_org: false) }
  scope :just_orgs, lambda { where(as_org: true) }

  # validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  # validates_attachment :image, presence: true, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :confirmable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :first_name, :last_name, :email, :password, :password_confirmation,
  # :remember_me, :pro_summary, :skill, :headline, :image_url, :experiences, :demo, :avatar

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String


  ## Confirmable
  field :confirmation_token,   :type => String
  field :confirmed_at,         :type => Time
  field :confirmation_sent_at, :type => Time
  field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time
  field :first_name,  type: String
  field :last_name,   type: String
  field :image_url,   type: String, default: "/images/original/missing.png"
  field :email,       type: String
  field :pro_summary, type: String
  field :skill,       type: String
  field :headline,    type: String
  field :demo,        type: Boolean, default: false
  field :has_resume,  type: Boolean, default: false
  field :original_user, type: Boolean, default: false
  field :sent_original_user_invite, type: Boolean, default: false

  # User choices
  field :privacy_setting, type: String, default: 'fully_public' # other options: 'only members' and 'only connections'
  field :allows_one_on_one_message_email, type: Boolean, default: true
  field :allows_friend_request_email, type: Boolean, default: true
  field :dont_show_add_password_page, type: Boolean, default: false

  field :as_org,      type: Boolean, default: false

  field :provider,    type: String
  field :uid,         type: String
  field :has_linkedin_account, type: Boolean, default: false
  field :added_password, type: Boolean, default: false

  has_and_belongs_to_many :colleges
  has_many :college_infos
  has_and_belongs_to_many :skills
  has_and_belongs_to_many :certs
  has_and_belongs_to_many :experiences
  has_and_belongs_to_many :roles
  has_and_belongs_to_many :subjects
  has_many :job_posts, dependent: :destroy
  has_and_belongs_to_many :conversations
  has_many :messages
  belongs_to :org

  search_in :first_name, :last_name, :email, :headline, :role, :subject_area,
            skills: :name,
            colleges: [ :name, :degree_type, :major ],
            experiences: [ :title, :employer, :school, :boro ],
            roles: :name,
            subjects: :name,
            org: [:name, :about, :org_website, :street_address, :borough, :org_type]

  has_mongoid_attached_file :avatar,
    :storage        => :s3,
    :bucket_name    => 'my-uploads',
    :path           => ':attachment/:id/:style.:extension',
    :s3_credentials => { bucket: "ep-#{ENV['EP_AWS_S3BUCKET']}-avatar", :access_key_id => ENV['EP_AWS_API_KEY'], :secret_access_key => ENV['EP_AWS_API_SECRET'] },
    :styles => { :medium => "120x120#", :thumb => "50x50#" }

  validates_attachment_content_type :avatar, :content_type => %w(image/jpeg image/jpg image/png)
  validates_attachment_size :avatar, :less_than => 5.megabytes

  accepts_nested_attributes_for :org

  validates_presence_of :first_name, :last_name, :email

  def self.users_with_info
    all_users = User.where(as_org: false)
    users_with_info = []
    all_users.shuffle.each do |user|
      if user.has_profile_info && user.has_profile_image?
        users_with_info << user
        break if users_with_info.count == 4
      end
    end
    return users_with_info
  end

  def name
    if as_org
      org.name
    else
      "#{first_name} #{last_name}"
    end
  end

  def update_name(full_name)
    split_full_name = full_name.split(' ', 2)
    self.first_name = split_full_name[0]
    self.last_name = split_full_name[1]
    self.save
  end

  def remove_all_friends
    friends.each do |friend|
      remove_friendship friend
    end

    pending_invited.each do |f|
      remove_friendship f
    end

    pending_invited_by.each do |f|
      remove_friendship f
    end
  end

  def self.connect_to_linkedin(auth, signed_in_resource=nil)
    if signed_in_resource.present? && signed_in_resource.email == auth.info.email
      signed_in_resource.sync_with_linkedin(signed_in_resource, auth)
      return signed_in_resource
    elsif signed_in_resource.nil?
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        registered_user.sync_with_linkedin(registered_user, auth)
        return registered_user
      else
        if new_user = User.new(
          first_name:auth.info.first_name,
          last_name:auth.info.last_name,
          headline:auth.info.headline,
          pro_summary:auth.info.summary,
          provider:auth.provider,
          uid:auth.uid,
          email:auth.info.email,
          password:Devise.friendly_token[0,20],
          has_linkedin_account:true,
          confirmed_at: DateTime.now
        )
          new_user.skip_confirmation!
          new_user.save!
          new_user.sync_with_linkedin(new_user, auth)
        end
      end
    end
    return new_user
  end

  def sync_with_linkedin(user, auth)
    client = LinkedIn::Client.new
    client.authorize_from_access(auth.extra.access_token.token, auth.extra.access_token.secret)

    user.image_url = client.picture_urls.all.first

    profile = client.profile(:fields => %w(positions educations skills headline))
    profile.to_hash

    user.headline = profile.headline
    user.save

    user_experiences = user.experiences.map { |exp| exp.linkedin_id }
    positions = profile.positions.to_hash
    if positions["all"].present?
      positions["all"].each do |p|

        company = p["company"]
        company.present? ? company = company["name"] : company = nil

        if !user_experiences.include? p["id"].to_s
          exp = Experience.create(title: p["title"],
                                  employer: p["company"]["name"],
                                  start_date: "#{p["start_date"]["month"]}/#{p["start_date"]["year"]}",
                                  is_current: p["is_current"],
                                  description: p["summary"],
                                  linkedin_id: p["id"])
          exp.save
          user.experiences << exp
          if p["end_date"]
            exp.end_date = "#{p["end_date"]["month"]}/#{p["end_date"]["year"]}"
            exp.save
          end
        end
      end
    end

    # skills = profile.skills.to_hash
    # if skills["all"].present?
    #   skills["all"].each do |s|
    #     if !user.skills.any? { |skill| skill.name == s["skill"]["name"] }
    #       skill = Skill.create(name: s["skill"]["name"])
    #       user.skills << skill
    #       user.save
    #     end
    #   end
    # end

    # user_educations = user.college_infos.map { |edu| edu.linkedin_id }
    # educations = profile.educations.to_hash
    # if educations["all"].present?
    #   educations["all"].each do |e|
    #     if !user_educations.include? e["id"].to_s
    #       if College.all.any? { |education| education.name == e["school_name"]}
    #         college = College.where(name: e["school_name"]).first
    #       else
    #         college = College.create(name: e["school_name"])
    #       end

    #       start_date = e["start_date"]
    #       start_date.present? ? start_date_year = start_date["year"] : start_date_year = nil

    #       end_date = e["end_date"]
    #       end_date.present? ? end_date_year = end_date["year"] : end_date_year = nil

    #       college.college_infos.create( start_date: start_date_year,
    #                                     end_date: end_date_year,
    #                                     degree_type: e["degree"],
    #                                     major: e["field_of_study"],
    #                                     user: user,
    #                                     linkedin_id: e["id"])
    #       user.colleges << college
    #     end
    #   end
    # end
  end

  def upload_resume_to_s3(user, resume)
    s3 = AWS::S3.new()
    bucket_path = Ep::Lib.bucket_path('resumes')
    object_path = resume.original_filename

    bucket = s3.buckets[bucket_path]
    if !bucket.exists?
      bucket = s3.buckets.create(bucket_path)
    end

    bucket.objects.create(user.id, resume.tempfile.read(), acl: :public_read)
  end

  def delete_resume_from_s3
    s3 = AWS::S3.new
    bucket = s3.buckets['ep-dev-resumes']
    name = self.id.to_s
    bucket.objects.delete(name)
    self.has_resume = false
    self.save
  end

  def delete_avatar_from_s3
    s3 = AWS::S3.new
    bucket = s3.buckets['ep-dev-avatar/avatars']
    name = self.id.to_s

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  autocomplete :college, :name, full: true

  def index
    @roles = Role.all.asc(:name)
    @subjects = Subject.all.asc(:name)
    @search_term = params[:search]

    role_ids = params[:filter_by_roles]
    subject_ids = params[:filter_by_subjects]

    if @search_term.present? || role_ids || subject_ids
      @users = User.just_users.desc(:created_at)
      @users = User.just_users.full_text_search(@search_term) if @search_term.present?
      if role_ids && subject_ids
        @users = @users.in(role_ids: role_ids).in(subject_ids: subject_ids)
      elsif role_ids || subject_ids
        @users = @users.in(role_ids: role_ids) if role_ids
        @users = @users.in(subject_ids: subject_ids) if subject_ids
      end
      @users = @users.desc(:created_at).paginate(page: params[:page], per_page: 10)
    else
      users_with_info = User.just_users.desc(:created_at).select { |user| user.has_profile_info }
      users_with_no_info = User.just_users.desc(:created_at).nin(id: users_with_info.map(&:id))
      users = users_with_info + users_with_no_info

      @users = users.paginate(page: params[:page], per_page: 10)
    end
  end

  def show
    if params[:id]
      @user = User.find params[:id]
    else
      @user = current_user
    end

    if @user.as_org
      redirect_to org_path(@user)
      return
    end

    @colleges = College.all
    @experiences = @user.experiences
    @roles = Role.all
    @subjects = Subject.all
    @suggestions = Ep::Lib.get_suggestions(@user)

    if current_user
      @conversations = @user.conversations.where(removed_for_ids: { '$nin' => [current_user.id.to_s] })
      @unread_messages_count = @user.unread_messages_count(@conversations)
    end

    if !@user.has_profile_info
      @other_people_that_have_info = User.users_with_info
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    name = params[:user][:name]
    headline = params[:user][:headline]

    if name.present?
      if @user.update_name(params[:user][:name])
        flash[:notice] =  "Saved!"
      else
        flash[:alert] =  "Error!"
      end
      render nothing: true
    elsif @user.update_attributes(params[:user].delete_if { |k, v| v.empty? })
      if params[:user][:password].present?
        sign_in(@user, :bypass => true)
        @user.set(added_password: true)
      end
      flash[:notice] = "Saved!"
      respond_to do |format|
        format.html { redirect_to user_path(@user) }
        format.json { render nothing: true }
        format.js
      end
    else
      flash[:alert] = @user.errors.full_messages
      respond_to do |format|
        format.html { redirect_to :back }
        format.json { render nothing: true }
        format.js
      end
    end
  end

  def destroy
    user = User.find(params[:id])
    user.remove_all_friends
    user.destroy

    redirect_to :root
  end

  def add_password
    @user = User.find(params[:id])
  end

  def add_avatar
    user = User.find(params[:id])
    if params[:user].present?
      accepted_formats = [".jpg", ".JPG", ".tif", ".TIF", ".png", ".PNG", ".gif", ".GIF", ".jpeg", ".JPEG"]
      avatar = params[:user][:avatar]

      if accepted_formats.include? File.extname(avatar.original_filename)
        user.avatar = avatar
        user.save
      else
        flash[:notice] = "Only files with extensions .jpg  .png .tif or .gif are allowed"
      end
    end

    redirect_to :back
  end

  def remove_avatar
    user = User.find(params[:id])
    user.avatar.clear
    user.image_url = ""
    user.delete_avatar_from_s3
    if user.save
      flash[:notice] = "Your profile picture has successfully been removed"
    else
     flash[:alert] =  "Error!"
    end
    redirect_to :back
  end

  def add_resume
    user = User.find(params[:id])
    if !params[:resume].nil?
      accepted_formats = [".doc", ".docx", ".pdf", ".txt"]
      resume = params[:resume]

      if accepted_formats.include? File.extname(resume.original_filename)
        user.upload_resume_to_s3(user, resume)
        user.has_resume = true
        user.save
      else
        flash[:notice] = "Only files with extensions .doc, .docx, .pdf or .txt are allowed"
      end
    end

    redirect_to :back
  end

  def remove_resume
    user = User.find(params[:id])
    user.delete_resume_from_s3
    user.has_resume = false
    user.save

    redirect_to :back
  end

  def my_jobs
    @user = User.find(params[:id])
    @search_term = params[:search]

    if @search_term.present?
      jobs = @user.job_posts.full_text_search(@search_term)
    else
      jobs = @user.job_posts
    end

    @jobs = jobs.asc(:created_at).paginate(page: params[:page], per_page: 10)
  end

  def refresh_progress
    user_progress = User.find(params[:id]).profile_progress
    render partial: "users/profile_progress", locals: {progress: user_progress}
  end

  private

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_add_avatar_form.html.erb
<div id="ep-profile-image__toggle" class="js-edit-form--file-upload js-profile-image-uploader-container collapse">
  <%= form_for user, :url => add_avatar_user_path(user), :html => { :method => "put", :multipart => true } do |f| %><br>

    <span class="ep-profile-image__placeholder">
      <input class="ep-profile-image__placeholder-input js-file-upload__placeholder-input" placeholder="Choose File" disabled="disabled" />
    </span>

    <div class="ep-profile-image__upload-fields">
      <%= f.file_field :avatar,
        :onchange => "_ep.validateProfileImageFile(this);",
        :data => { :max_file_size => 5.megabytes },
        "data-filename-placement"=> "inside",
        class: "ep-profile-image__file-field js-file-upload__file-field js-profile-image__file-field",
        required: true %>

      <%= f.submit "Upload", class: "btn btn-primary js-file-upload__submit", disabled: true  %>
      <%= content_tag :div, 'Cancel', class: 'btn btn-default', :data => { toggle: "collapse", target: "#ep-profile-image__toggle" } %>
      <%= link_to 'Remove', remove_avatar_user_path(user), method: :put, class: 'btn btn-primary btn-warning' %>
    </div>
  <% end %>
</div>

app/views/users/_certs.html.erb
<div class="ep-profile-section__header">
  <h4>Certification</h4>
</div>
<div class="ep-certs ep-profile-section__body js-section-container">
  <div class="ep-profile-section__item-holder">
    <% for cert in @user.certs %>
      <div class="ep-cert">
        <%= cert.name %>
          <% if @user == current_user %>
            <%= link_to cert_path(cert), method: :delete, remote: true, class: 'js-edit js-delete' do %>
            <i class="fa fa-times"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  <% if @user == current_user %>
    <a class="<%= @user.certs.present? ? 'js-edit' : '' %>  js-edit-section-item"></i> + Add</a>
    <div id="ep-add-cert" class="js-edit-form ep-form ep-edit-form">
      <%= form_for Cert.new, remote: true do |f| %>
        <div class="ep-form__profile-form-field">
          <%= f.label 'Certification', :class => 'ep-form__label' %><br>
          <%= f.text_field :name, autofocus: true, :class => 'ep-form__text-field', required: true %>
        </div>
        <%= f.submit 'Add', :class => 'btn btn-primary' %>
        <%= content_tag :div, 'cancel', class: 'ep-cancel-edit btn btn-default' %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/_job.html.erb
<div class="js-section-container ep-experience-container">
	<div id="ep-edit-job-<%= experience.id %>" class="ep-experience-edit-form ep-edit-form js-edit-form">
		<%= render :partial => '../views/experiences/edit_form', locals: { experience: experience } %>
	</div>
	<div class="js-experience ep-experience js-section-item">
		<div class="ep-title-container">
			<h5>
				<%= experience.title %> <span><%= place_of_work(experience) %></span>
				<span class="nycdoe"><%= experience.employer == 'NYCDOE' ? "(#{experience.employer})" : '' %></span>
			</h5>
		</div>
		<p class="ep-experience-meta">
			<%= experience.employer if experience.school.present? && experience.employer.present? %>
		</p>
		<p class="ep-experience-meta">
			<%= experience.boro.present? ? experience.boro : '' %>
			<%= " |" if  experience.boro.present? && ( experience.district.present? || experience.start_date.present? )%>
			<%= experience.district.present? ? "District: #{experience.district}" : '' %>
			<%= " |" if  experience.district.present? && experience.start_date.present? %>
			<% if experience.start_date.present? && experience.end_date.present? %>
				<%= experience.start_date %> - <%= experience.end_date %>
			<% elsif experience.start_date.present? && !experience.end_date.present? %>
				<%= "#{experience.start_date} - present" %>
			<% end %>
		</p>
		<p><%= h(experience.description).gsub(/\n/, '<br/>').html_safe %></p>
	</div>
	<% if @user == current_user %>
		<a class="js-edit-section-item js-edit">Edit |</a>
		<%= link_to ' Delete', experience_path(experience), method: :delete, remote: true, class: 'js-edit js-delete' %>
	<% end %>
	<hr>
</div>

app/views/users/_pro_summary.html.erb
<div class="ep-profile-section__header">
	<h4>
		Pro summary
		<% if @user == current_user %>
			<a class="ep-edit-pro-summary"><i class="fa fa-pencil"></i> Edit</a>
		<% end %>
	</h4>
</div>

<div class="ep-profile-section__body">
	<p><%= best_in_place user, :pro_summary, :type => :textarea, activator: '.ep-edit-pro-summary' %></p>
</div>

app/views/users/_profile_actions.html.erb
<% if !user_signed_in? %>
  <p><i class="fa fa-plus"></i>&nbsp <%= link_to "Sign in", new_session_path(user) %> to connect</p>

<% elsif current_user == user %>
  <% %>

<% elsif !current_user.connected_with? user %>
  <p class='ep-profile-connection-request'>
    <i class="fa fa-plus"></i>
    <span class='ep-profile-connection-request-link ep-link-style' data-toggle="modal" data-target="#ep-confirm__connection-request">
      Connect
    </span>
  </p>

<% elsif current_user.friend_with? user %>
  <p><i class="fa fa-plus"></i>&nbsp Connected </p>

<% elsif current_user.invited? user %>
  <p><i class="fa fa-plus"></i>
  Pending connection
  </p>

<% elsif current_user.invited_by? user %>
  <p><i class="fa fa-plus"></i>
  Pending connection
  <%= link_to "(Approve)", friendship_path(user), method: :put, remote: true, class: 'ep-approve' %></p>

<% end %>

<% if current_user == user %>
  <p>
    <i class="fa fa-envelope"></i> <%= link_to 'My messages', user_conversations_path(user) %>
    <% if @unread_messages_count > 0 %>
      <span class="ep-unread-messages-alert"><%= "#{@unread_messages_count}" %></span>
    <% end %>
  </p>
<% else %>
  <% if user_signed_in? %>
    <p data-toggle="modal" data-target=".ep-message-modal">
      <i class="fa fa-envelope"></i> <a>Send a message</a>
    </p>
  <% else %>
   <p><i class="fa fa-envelope"></i> <%= link_to "Sign in", new_session_path(user) %> to send a message</p>
  <% end %>
<% end %>
<p>
  <% if user.has_resume %>
    <i class="fa fa-file-text"></i>&nbsp
    <% if user == current_user %>
      <%= link_to "Edit your resume", "#", class: 'js-edit-resume' %>
    <% else %>
      <%= link_to "Download #{user.first_name + '\'s'} resume", "https://s3.amazonaws.com/ep-dev-resumes/#{user.id}" %>
    <% end %>
    <br>
    <span class="ep-edit-resume-options js-edit-resume-options">
      <%= link_to "Download", "https://s3.amazonaws.com/ep-dev-resumes/#{user.id}", target: "_blank" %> |
      <a data-toggle="collapse" data-target="#ep-resume__toggle">Update</a> |
      <span class='ep-link-style' data-toggle="modal" data-target="#ep-confirm__remove-resume">
        Remove
      </span> |
      <%= link_to "Cancel", "#", class: 'js-cancel-edit-resume' %>
    </span>
  <% end %>

  <% if user == current_user %>
    <div class="ep-profile-image__uploader-container">
      <% if !user.has_resume %>
        <i class="fa fa-file-text"></i>
        <a data-toggle="collapse" data-target="#ep-resume__toggle">
          Upload your resume
        </a>
      <% end %>
      <div id="ep-resume__toggle" class="js-edit-form--file-upload js-resume-uploader-container collapse">
        <%= form_for user, :url => add_resume_user_path(user), :html => { method: :put, :multipart => true } do |f| %><br>

          <span class="ep-resume__placeholder">
            <input class="ep-resume__placeholder-input js-file-upload__placeholder-input" placeholder="Choose File" disabled="disabled" />
          </span>
          <%= file_field_tag :resume,
              :onchange => "_ep.validateResumeFile(this);",
              :data => { :max_file_size => 5.megabytes },
              "data-filename-placement"=> "inside",
              class: "ep-resume__file-field js-resume__file-field js-file-upload__file-field",
              required: true %>
          <div>
            <br>
            <%= f.submit "Upload", class: "btn btn-primary js-file-upload__submit", disabled: true %>
            <%= content_tag :div, 'Cancel', class: 'btn btn-default', :data => { toggle: "collapse", target: "#ep-resume__toggle" } %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</p>
<!-- <p><i class="fa fa-folder-open"></i> View <%= user.first_name %>'s portfolio</p> -->
<% if current_user == user %>
  <p><i class="fa fa-linkedin-square"></i>&nbsp<%= link_to "Import from Linkedin",user_omniauth_authorize_path(:linkedin) %></p>
<% end %>

<% if current_user == user && user.has_job_posts? %>
  <p><i class="fa fa-th-list"></i> <%= link_to 'My job posts', my_jobs_user_path(user) %></p>
<% end %>

<% if current_user == user %>
  <p class='js-edit-mode'><i class="fa fa-pencil-square"></i><a> Edit my profile</a></p>
  <p class='js-exit-edit-mode js-edit'><i class="fa fa-pencil-square"></i><a> Done Editing</a></p>
  <div class="ep-profile-progress"  data-url="<%= refresh_progress_user_path(@user) %>">
    <%= render partial: 'profile_progress', locals: { progress: user.profile_progress } %>
  </div>
<% end %>

<div id="ep-confirm__connection-request" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content ep-content--send-message">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <div class="modal-header">
        <h4 class="modal-title modal-title--gray">Connect with <%= @user.name %>?</h4>
      </div><br>
      <div class="ep-confirm__btns">
        <%= link_to "Connect", friendships_path(id: user.id), method: :post, remote: true, class: 'btn btn-primary', data: { dismiss: "modal"} %>
        <div class="ep-cancel-edit btn btn-default" data-dismiss="modal">cancel</div>
      </div>
    </div>
  </div>
</div>

<div id="ep-confirm__remove-resume" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content ep-content--send-message">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <div class="modal-header">
        <h4 class="modal-title modal-title--gray">Are you sure you'd like to remove your resume?</h4>
      </div><br>
      <div class="ep-confirm__btns">
        <%= link_to 'Remove', remove_resume_user_path(user), method: :put, class: 'btn btn-primary' %>
        <div class="ep-cancel-edit btn btn-default" data-dismiss="modal">cancel</div>
      </div>
    </div>
  </div>
</div>

app/views/users/_roles.html.erb
<h5>Roles</h5>
  <% user.roles.each_with_index do |role, i| %>
    <span class="ep-role">
      <% if user == current_user %>
        <%= link_to role_path(role), method: :delete, remote: true, class: 'js-edit js-delete' do %>
          <i class="fa fa-times"></i>
        <% end %>
      <% end %>
      <span><%= role.name %></span><%= "," unless i == user.roles.count - 1 %>
    </span>
  <% end %>

  <% if user.roles.blank? && user = current_user %>
    <span>No roles yet</span>
  <% end %>
  <br>
<div class="js-section-container">
  <% if current_user && user == current_user %>
    <a class="js-edit-section-item ep-add-role js-add-role <%= user.roles.present? ? 'js-edit' : '' %>">+ Add</a>
    <div id="ep-add-role" class="js-edit-form ep-edit-form">
      <%= form_for Role.new, remote: true do |f| %>
        <div class="ep-form__profile-form-field">
          <%= collection_select(:role, :id, @roles,
                  :id, :name,
                 {:prompt => 'Select a role'}) %>
        </div>
        <%= f.submit 'Add', :class => 'btn btn-primary' %>
        <%= content_tag :div, 'cancel', class: 'ep-cancel-edit btn btn-default' %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/_skills.html.erb
<div class="ep-profile-section__header">
	<h4>Skills</h4>
</div>
<div class="ep-skills ep-profile-section__body js-section-container">
	<div class="ep-profile-section__item-holder">
		<% for skill in @user.skills %>
			<div class="ep-skill">
				<%= skill.name %>
					<% if @user == current_user %>
						<%= link_to skill_path(skill), method: :delete, remote: true, class: 'js-edit js-delete' do %>
						<i class="fa fa-times"></i>
					<% end %>
				<% end %>
			</div>
		<% end %>
	</div>
	<% if @user == current_user %>
		<a class="<%= @user.skills.present? ? 'js-edit' : '' %>  js-edit-section-item"></i> + Add</a>
		<div id="ep-add-skill" class="js-edit-form ep-form ep-edit-form">
			<%= form_for Skill.new, remote: true do |f| %>
				<div class="ep-form__profile-form-field">
					<%= f.label :name, :class => 'ep-form__label' %>
				 	<%= f.text_field :name, autofocus: true, :class => 'ep-form__text-field', required: true %>
				</div>
		    <%= f.submit 'Add', :class => 'btn btn-primary' %>
		    <%= content_tag :div, 'cancel', class: 'ep-cancel-edit btn btn-default' %>
		 	<% end %>
		</div>
	<% end %>
</div>