config/routes.rb
Ep::Application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: "registrations",
    sessions: "sessions",
    passwords: "passwords"
  }

  devise_scope :user do
    authenticated :user do
      root :to => 'users#show', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/registrations#new'
    end
  end

  resources :users do
    get :autocomplete_college_name, :on => :collection
    member do
      put :add_avatar
      put :remove_avatar
      put :add_resume
      put :remove_resume
      get :my_jobs
      get :refresh_progress
    end

    authenticate :user do
      resources :conversations do
        member do
          put :restore
        end
      end
    end

    resources :connections, only: [:index]
  end

  resources :colleges, only: [:create]
  resources :college_infos, only: [:edit, :update, :destroy]
  resources :experiences, only: [:create, :edit, :update, :destroy]
  resources :skills, only: [:create, :destroy]
  resources :certs, only: [:create, :destroy]
  resources :roles, only: [:create, :destroy]
  resources :subjects, only: [:create, :destroy]
  resources :job_posts
  resources :messages
  resources :job_maps, only: [:index]
  resources :friendships, only: [:create, :update, :destroy]

  resources :orgs, only: [:show, :index, :update]

  get '/terms' => 'pages#terms', as: :terms
  get '/privacy_policy' => 'pages#privacy_policy', as: :privacy_policy

end

app/models/job_post.rb
class JobPost
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Search
  include Geocoder::Model::Mongoid

  after_validation :geocode
  geocoded_by :address_or_name_for_geocode

  field :title,         type: String
  field :organization,  type: String
  field :neighborhood,  type: String
  field :contact_info,  type: String
  field :org_website,   type: String
  field :description,   type: String

  field :street_address,  type: String
  field :city,            type: String
  field :state,           type: String
  field :zip,             type: String
  field :coordinates,     type: Array

  # Ideed job fields
  field :indeed_key
  field :indeed_location
  field :indeed_url
  field :indeed_date

  belongs_to :user
  belongs_to :subject
  belongs_to :role
  belongs_to :location

  search_in :title, :organization, :location, :neighborhood, :contact_info, :org_website, :description

  def address
    "#{self.street_address} #{self.city} #{self.state} #{self.zip}"
  end

  def city_state
    "#{self.city}, #{self.state}"
  end

  private

  def address_or_name_for_geocode
    if self.indeed_key.present?
      return "#{self.organization} #{self.indeed_location}"
    else
      if self.street_address.present?
        return self.address
      else
        if self.user && self.user.as_org
          if self.user.org.street_address.present?
            return self.user.org.address
          else
            return self.user.org.name
          end
        end
      end
    end
  end

end

app/controllers/job_posts_controller.rb
class JobPostsController < ApplicationController

  def index
    @search_term = params[:search]
    @roles = Role.all.asc(:name)
    @locations = Location.all.asc(:name)

    role_ids = params[:filter_by_roles]
    location_ids = params[:filter_by_locations]

    if @search_term.present? || role_ids || location_ids
      if @search_term.present?
        jobs = JobPost.full_text_search(@search_term)
      else
        jobs = JobPost.all
      end

      if role_ids && location_ids
        location_names = Location.in(id: location_ids).pluck(:name).map { |name| Regexp.new(name, 'i')}
        role_names = Role.in(id: role_ids).pluck(:name).map { |name| Regexp.new(name, 'i')}

        jobs_filtered_by_location = jobs.where( location_id: { :$in => location_ids } ) + jobs.where( indeed_location: { :$in => location_names } )
        jobs_filtered_by_location = JobPost.all.in( id: jobs_filtered_by_location.map(&:id) )
        jobs = jobs_filtered_by_location.where( role_ids: { :$in => location_names } ) + jobs_filtered_by_location.where( title: { :$in => role_names } )

        @jobs = jobs.sort_by(&:created_at).reverse.paginate(page: params[:page], per_page: 10)
      elsif role_ids || location_ids
        if location_ids
          location_names = Location.in(id: location_ids).pluck(:name).map { |name| Regexp.new(name, 'i')}
          jobs = jobs.where( location_id: { :$in => location_ids } ) + jobs.where( indeed_location: { :$in => location_names } )
        end

        if role_ids
          role_names = Role.in(id: role_ids).pluck(:name).map { |name| Regexp.new(name, 'i')}
          jobs = jobs.where( role_id: { :$in => role_ids }) + jobs.where( title: { :$in => role_names } )
        end

        @jobs = jobs.sort_by(&:created_at).reverse.paginate(page: params[:page], per_page: 10)
      else
        @jobs = jobs.desc(:created_at).paginate(page: params[:page], per_page: 10)
      end
    else
      @jobs = JobPost.desc(:created_at).paginate(page: params[:page], per_page: 10)
    end
  end

  def show
    @job = JobPost.find(params[:id])
    job_title = @job.title
    job_location = @job.location
    @similar_jobs = JobPost.ne(id: @job.id).or(title: (/#{job_title}/i)).or(location: (/#{job_location}/i)).shuffle.first(5)
    @random_jobs = JobPost.all.shuffle.first(5) if @similar_jobs.blank?
  end

  def new
    @job_post = JobPost.new()
    @random_jobs = JobPost.all.shuffle.first(5) if @similar_jobs.blank?
  end

  def create
    @job_post = JobPost.create(params[:job_post])
    @job_post.user = current_user
    if @job_post.save
      flash[:notice] =  "Saved!"
    else
      flash[:alert] =  "Error!"
    end

    redirect_to job_post_path(@job_post)
  end

  def update
    @job_post = JobPost.find(params[:id])
    @job_post.update_attributes(params[:job_post])
  end

  def destroy
    @job_post = JobPost.find(params[:id])
    @job_post.destroy

    redirect_to job_posts_path
  end
end

app/views/job_posts/_form_fields.html.erb
<div class="ep-form__profile-form-field ep-form__job-field">
  <%= f.label :title, :class => 'ep-form__label' %><br>
  <%= f.text_field :title, class: 'ep-form__text-field ep-form__job-text-field' %>
</div>

<div class="ep-form__profile-form-field ep-form__job-field">
  <%= f.label :organization, :class => 'ep-form__label' %><br>
  <%= f.text_field :organization, class: 'ep-form__text-field ep-form__job-text-field' %>
</div>

<div class="ep-form__profile-form-field ep-form__job-field">
  <%= f.label :organization_website, :class => 'ep-form__label' %><br>
  <%= f.text_field :org_website, class: 'ep-form__text-field ep-form__job-text-field' %>
</div>

<div class="ep-form__profile-form-field ep-form__job-field">
  <%= f.label :street_address, :class => 'ep-form__label' %><br>
  <%= f.text_field :street_address, class: 'ep-form__text-field ep-form__job-text-field' %>
</div>

<div class="ep-form__profile-form-field ep-form__job-field">
  <%= f.label :city, :class => 'ep-form__label' %><br>
  <%= f.text_field :city, class: 'ep-form__text-field ep-form__job-text-field' %>
</div>

<div class="ep-form__profile-form-field ep-form__job-field">
  <%= f.label :state, :class => 'ep-form__label' %><br>
  <%= f.text_field :state, class: 'ep-form__text-field ep-form__job-text-field--state' %>
</div>

<div class="ep-form__profile-form-field ep-form__job-field">
  <%= f.label :zip, :class => 'ep-form__label' %><br>
  <%= f.text_field :zip, class: 'ep-form__text-field ep-form__job-text-field--zip' %>
</div>

<div class="ep-form__profile-form-field ep-form__job-field">
  <%= f.label :neighborhood, :class => 'ep-form__label' %><br>
  <%= f.text_field :neighborhood, class: 'ep-form__text-field ep-form__job-text-field' %>
</div>

<div class="ep-form__profile-form-field ep-form__job-description-field">
  <%= f.label :description, :class => 'ep-form__label' %><br>
  <%= f.text_area :description, height: '300px', class: 'ep-form__text-field ep-form__job-description' %>
</div>

<div class="ep-form__profile-form-field ep-form__job-description-field">
  <%= f.label 'How to apply', :class => 'ep-form__label' %><br>
  <%= f.text_area :contact_info, class: 'ep-form__text-field ep-form__how-to-apply' %>
</div>

app/views/job_posts/_form_fields_for_edit.html.erb
<div class="ep-form__profile-form-field ep-form__job-field">
  <%= f.label :title, :class => 'ep-form__label' %><br>
  <%= f.text_field :title, class: 'ep-form__text-field ep-form__job-text-field' %>
</div>

<div class="ep-form__profile-form-field ep-form__job-field">
  <%= f.label :organization, :class => 'ep-form__label' %><br>
  <%= f.text_field :organization, class: 'ep-form__text-field ep-form__job-text-field' %>
</div>

<div class="ep-form__profile-form-field ep-form__job-field">
  <%= f.label :organization_website, :class => 'ep-form__label' %><br>
  <%= f.text_field :org_website, class: 'ep-form__text-field ep-form__job-text-field' %>
</div>

<div class="ep-form__profile-form-field ep-form__job-field">
  <%= f.label :street_address, :class => 'ep-form__label' %><br>
  <%= f.text_field :street_address, class: 'ep-form__text-field ep-form__job-text-field' %>
</div>

<div class="ep-form__profile-form-field ep-form__job-field">
  <%= f.label :city, :class => 'ep-form__label' %><br>
  <%= f.text_field :city, class: 'ep-form__text-field ep-form__job-text-field' %>
</div>

<div class="ep-form__profile-form-field ep-form__job-field">
  <%= f.label :state, :class => 'ep-form__label' %><br>
  <%= f.text_field :state, class: 'ep-form__text-field ep-form__job-text-field--state' %>
</div>

<div class="ep-form__profile-form-field ep-form__job-field">
  <%= f.label :zip, :class => 'ep-form__label' %><br>
  <%= f.text_field :zip, class: 'ep-form__text-field ep-form__job-text-field--zip' %>
</div>

<div class="ep-form__profile-form-field ep-form__job-field">
  <%= f.label :neighborhood, :class => 'ep-form__label' %><br>
  <%= f.text_field :neighborhood, class: 'ep-form__text-field ep-form__job-text-field' %>
</div>

<div class="ep-form__profile-form-field ep-form__job-description-field">
  <%= f.label :description, :class => 'ep-form__label' %><br>
  <%= f.text_area :description, height: '300px', class: 'ep-form__text-field ep-form__job-description' %>
</div>

<div class="ep-form__profile-form-field ep-form__job-description-field">
  <%= f.label 'How to apply', :class => 'ep-form__label' %><br>
  <%= f.text_area :contact_info, class: 'ep-form__text-field ep-form__how-to-apply' %>
</div>

app/views/job_posts/_job_posts.html.erb
<% if jobs.present? %>
  <% jobs.each do |job| %>
    <tr>
      <td>
        <div class="ep-index__meta">
          <p><%= link_to job.title, job_post_path(job) %></p>
          <p><%= job.organization %></p>
          <p class="ep-index__description"><%= job.description.truncate(60) %></p>
        </div>
      </td>
      <td>
        <div class="ep_index--connection js_jobss--connection-<%= job.id %>">
          <p class="ep-index__info-right">
            <% if job.indeed_key.present? %>
              Indeed job post<br>
              <%= job.indeed_location %><br>
            <% else %>
              <%= job.neighborhood if job.neighborhood %><br>
              <%= job.location.name if job.location %><br>
              <%= job.role.name if job.role %><br>
            <% end %>
          </p>
        </div>
      </td>
    </tr>
  <% end %>
<% else %>
  <p>Sorry, no matches. Try broadening your search.</p>
<% end %>

app/views/job_posts/_show_job.html.erb
<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['EP_GOOGLE_MAPS_KEY'] %>">
</script>

<% if job.coordinates.present? %>
  <% lng = job.coordinates[0] %>
  <% lat = job.coordinates[1] %>
<% end %>

<script type="text/javascript">

  var myLatlng = new google.maps.LatLng(<%= lat %>,<%= lng %>);

  var styles = [{"featureType":"landscape.natural","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"color":"#e0efef"}]},{"featureType":"poi","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"hue":"#1900ff"},{"color":"#d3d3d3"}]},{"featureType":"road","elementType":"geometry","stylers":[{"lightness":100},{"visibility":"simplified"}]},{"featureType":"transit.line","elementType":"geometry","stylers":[{"visibility":"on"},{"lightness":700}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#3bafda"}]}]

  $(function(){
    var mapOptions = {
      center: myLatlng,
      zoom: 14,
      styles: styles
    };
    var map = new google.maps.Map(document.getElementById('map-canvas'),
        mapOptions);

    var marker = new google.maps.Marker({
      position: myLatlng
    });

    marker.setMap(map);
  })

</script>

<div class="ep-show-job__options pull-right">
  <% if user_signed_in? && job.user == current_user %>
    <a class='js-edit-section-item--job'> Edit</a>
    |
    <span class='ep-link-style' data-toggle="modal" data-target="#ep-confirm__delete-job">
      Remove
    </span>
  <% end %>
</div>
<div class="js-section-item">
  <div class="page-header ep-job-info__page-header">
    <h3><%= job.title %></h3>
    <% if job.has_user? && job.user.as_org %>
      <p style="font-size:16px;">at <%= link_to job.user.name, org_path(job.user) %></p>
    <% elsif (job.has_user? && !job.user.as_org) || job.indeed_key.present? %>
      <p style="font-size:16px;">at <%= job.organization %></p>
    <% end %>

    <% if job.indeed_key.present? %>
      <span class="ep-gray">
        <%= job.indeed_location %>
      </span>
    <% else %>
      <span class="ep-gray">
        <%= job.neighborhood if job.neighborhood %>
        <%= job.city_state if job.city_state && job.neighborhood.blank? %>
      </span>
    <% end %>

    <% if job.org_website %>
      | <span><%= link_to 'Website', "http://#{job.org_website}", target: '_blank' %></span>
    <% end %>

    <span class="pull-right ep-gray" style="font-size:12px;">
      Posted on: <%= job.indeed_key.present? ? job.indeed_date.to_datetime.strftime("%b %d, %Y") : job.created_at.strftime("%b %d, %Y") %>
    </span>
  </div>

  <div class="ep-job-info__description">
    <% if job.description.present? %>
      <h4>Description</h4>
      <p><%= h(job.description).gsub(/\n/, '<br/>').html_safe %></p>
      <hr>
    <% end %>
    <% if job.indeed_key.present? %>
      <p><%= link_to "View full post on indeed", "#{job.indeed_url}", target: '_blank' %></p>
    <% end %>
    <% if job.contact_info.present? %>
      <h4>How to apply</h4>
      <p><%= job.contact_info %></p>
    <% end %>
  </div>
  <% if job.coordinates.present? %>
    <div class="ep-job-info__map" style="height:300px; width:100%;">
      <div id="map-canvas" class="ep-job-info__map-canvas" style="width: 88%; height: 100%;"></div>
    </div>
  <% end %>
</div>
<br>
<div class='ep-form ep-add-job-form ep-edit-form ep-edit-form--job js-edit-form'>
  <h3>Edit job post</h3>
  <hr>
  <%= form_for job, method: :put, remote: true do |f| %>
    <%= render partial: 'form_fields_for_edit', locals: { f: f } %>
    <div class="ep-form__clear">
      <%= f.submit 'Save', :class => 'btn btn-primary' %>
      <%= content_tag :div, 'cancel', class: 'ep-cancel-edit btn btn-default' %>
    </div>
  <% end %>
</div>
<br>

<div id="ep-confirm__delete-job" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content ep-content--send-message">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <div class="modal-header">
        <h4 class="modal-title modal-title--gray">Delete this job?</h4>
      </div><br>
      <div class="ep-confirm__btns">
        <%= link_to 'Remove', job_post_path(job), class: 'btn btn-primary', method: :delete %>
        <div class="ep-cancel-edit btn btn-default" data-dismiss="modal">cancel</div>
      </div>
    </div>
  </div>
</div>

app/views/job_posts/index.html.erb
<div class="row-fluid"><br><br><br><br>
  <div class="ep-search col-sm-3 white-bg">
    <h4>
      <%= link_to job_maps_path, class: 'ep-link-to-job-maps' do %>
        <i class="fa fa-globe"></i> Jobs Map
      <% end %>
    </h4>

    <h3>Find jobs</h3>
    <%= form_tag job_posts_path, method: :get, remote: true, class: 'js-search-form' do %>

      <%= text_field_tag 'search', @search_term, placeholder: 'Search jobs...', class: "js-search-form__text-field ep-search-form__text-field" %>

      <h4>Filter by location</h4>
      <% @locations.each do |location| %>
        <%= check_box_tag 'filter_by_locations[]', location.id, false, id: "#{location.id}", class: 'js-search-form__check-box' %>
        <%= label_tag 'filter_by_location', location.name, class: 'ep-filter-label', for: "#{location.id}"   %><br>
      <% end %>

      <h4>Filter by role</h4>
      <% @roles.in(name: ["Administrator", "Teacher"]).desc(:name).each do |role| %>
        <%= check_box_tag 'filter_by_roles[]', role.id, false, id: "#{role.id}", class: 'js-search-form__check-box' %>
        <%= label_tag 'filter_by_roles', role.name, class: 'ep-filter-label', for: "#{role.id}"  %><br>
      <% end %>

      <% @roles.nin(name: ["Administrator", "Teacher"]).desc(:name).each do |role| %>
        <%= check_box_tag 'filter_by_roles[]', role.id, false, id: "#{role.id}", class: 'js-search-form__check-box' %>
        <%= label_tag 'filter_by_roles', role.name, class: 'ep-filter-label', for: "#{role.id}"  %><br>
      <% end %>
   <% end %>
  </div>

  <div class="ep-index col-sm-8 white-bg">
    <div class="page-header">
      <% if user_signed_in? %>
        <a class="pull-right" data-toggle="collapse" data-target="#ep-app-job__toggle">Post a job</a>
      <% end %>
      <h3>Jobs</h3>
      <% if user_signed_in? %>
        <div id="ep-app-job__toggle" class="collapse">
          <div class='ep-form js-edit-form'>
            <%= form_for JobPost.new do |f| %>
              <%= render partial: 'form_fields', locals: { f: f, org: current_user && current_user.as_org ? current_user.org : nil } %>
              <div class="ep-form__clear">
                <%= f.submit 'Add', :class => 'btn btn-primary' %>
                <%= content_tag :div, 'cancel', class: 'btn btn-default', :data => { toggle: "collapse", target: "#ep-app-job__toggle" } %>
                <br><br>
                <p class="ep-gray">This job post will expire in 90 days.</p>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <table class="table ep-index__table">
      <tbody class="ep-index__items">
        <%= render partial: 'job_posts/job_posts', locals: { jobs: @jobs } %>
      </tbody>
    </table>
    <div class="js-will-page">
      <%= will_paginate @jobs %>
    </div>
  </div>
</div>

app/views/job_posts/new.html.erb
<div class="row-fluid"><br><br><br><br>

  <div class="ep-similar-jobs col-sm-3 white-bg">
    <h4>
      <%= link_to job_maps_path, class: 'ep-link-to-job-maps' do %>
        <i class="fa fa-globe"></i> Jobs Map
      <% end %>
    </h4>
    <h3>Other Jobs</h3><br><br>
    <% @random_jobs.each do |job| %>
      <p><%= link_to job.title.truncate(30), job_post_path(job) %></p>
      <% if job.indeed_key %>
        <p><%= job.indeed_location %></p>
      <% else %>
        <p><%= job.location ? job.location.name : 'Unknown Location' %></p>
      <% end %>
      <hr>
    <%end %>
  </div>

  <div class="ep-show-job col-sm-8 white-bg">
    <br>
    <h3>Post a job</h3>
    <% if current_user %>
      <div class='ep-form js-edit-form'>
        <%= form_for @job_post do |f| %>
          <%= render partial: 'form_fields', locals: { f: f, org: current_user && current_user.as_org ? current_user.org : nil } %>
          <div class="ep-form__clear">
            <%= f.submit 'Add', :class => 'btn btn-primary' %>
            <%= content_tag :div, 'cancel', class: 'btn btn-default', :data => { toggle: "collapse", target: "#ep-app-job__toggle" } %>
            <br><br>
            <p class="ep-gray">This job post will expire in 90 days.</p>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="ep-sign-in-to-post-job">
        <br>
        <% user = User.new() %>
        <p><%= link_to "Sign in", new_session_path(user) %> or <%= link_to "create", new_registration_path(user) %> an account to post a job.</p>
      </div>
    <% end %>
    <br>
  </div>

</div>

app/views/job_posts/show.html.erb
<div class="js-section-container row-fluid"><br><br><br><br>

    <div class="ep-similar-jobs col-sm-3 white-bg">
      <h4>
        <%= link_to job_maps_path, class: 'ep-link-to-job-maps' do %>
          <i class="fa fa-globe"></i> Jobs Map
        <% end %>
      </h4>
      <% if @similar_jobs.present? %>
        <h3>Similar Jobs</h3><br><br>
        <% @similar_jobs.each do |job| %>
          <p><%= link_to job.title.truncate(30), job_post_path(job) %></p>
          <% if job.indeed_key %>
            <p><%= job.indeed_location %></p>
          <% else %>
            <p><%= job.location ? job.location.name : 'Unknown Location' %></p>
          <% end %>
          <hr>
        <% end %>
      <% else %>
          <h3>Other Jobs</h3><br><br>
          <% @random_jobs.each do |job| %>
            <p><%= link_to job.title.truncate(30), job_post_path(job) %></p>
            <% if job.indeed_key %>
              <p><%= job.indeed_location %></p>
            <% else %>
              <p><%= job.location ? job.location.name : 'Unknown Location' %></p>
            <% end %>
            <hr>
          <%end %>
      <% end %>
    </div>

    <div class="ep-show-job col-sm-8 white-bg">
      <%= render partial: 'show_job', locals: { job: @job } %>
    </div>
  </div>
</div>